package com.github.pushingice;

import java.util.Base64;
import java.util.Properties;
import java.util.Random;

public class Message {

    private String messageType;
    private String fkMessageType = "";
    private long fkId = 0;
    private long id;
    private long timestamp;
    private String content;

    public Message(Properties props, Random random, String messageType) {
        this.messageType = messageType;
        id = random.nextLong();
        byte[] rawContent = new byte[Integer.parseInt(
                props.getProperty(Constants.CONFIG_MESSAGE_BYTES))];
        random.nextBytes(rawContent);
        content = Base64.getEncoder().encodeToString(rawContent);
    }

    public Message(String messageType, long id, String fkMessageType,
                   long fkId, String content) {
        this.messageType = messageType;
        this.id = id;
        this.content = content;
        this.fkMessageType = fkMessageType;
        this.fkId = fkId;
    }


    public Message copy() {
        return new Message(messageType, id, fkMessageType, fkId, content);
    }

    public Long getId() {
        return id;
    }

    public String getContent() {
        return content;
    }

    public String getMessageType() {
        return messageType;
    }

    public String getFkMessageType() {
        return fkMessageType;
    }

    public long getFkId() {
        return fkId;
    }

    public void setFkMessageType(String fkMessageType) {
        this.fkMessageType = fkMessageType;
    }

    public void setFkId(long fkId) {
        this.fkId = fkId;
    }

    // Generated by IntelliJ
    @Override
    public String toString() {
        return "Message{" +
                "messageType='" + messageType + '\'' +
                ", id=" + id +
                ", fkMessageType='" + fkMessageType + '\'' +
                ", fkId=" + fkId +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Message message = (Message) o;

        if (fkId != message.fkId) return false;
        if (id != message.id) return false;
        if (timestamp != message.timestamp) return false;
        if (!fkMessageType.equals(message.fkMessageType)) return false;
        if (!messageType.equals(message.messageType)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = messageType.hashCode();
        result = 31 * result + fkMessageType.hashCode();
        result = 31 * result + (int) (fkId ^ (fkId >>> 32));
        result = 31 * result + (int) (id ^ (id >>> 32));
        result = 31 * result + (int) (timestamp ^ (timestamp >>> 32));
        return result;
    }
}
